<a href="https://colab.research.google.com/github/K-Kamonrat/DPDM/blob/master/Data103.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np #จัดการตัวเลข มองเป็น matrix

In [5]:
A = np.array([[1,2,3],[4,5,6]]) #พิมพ์แถวเรียงต่อกัน
A

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
A.T #transpost

array([[1, 4],
       [2, 5],
       [3, 6]])

In [7]:
A.dot(A.T) #.dot()  การคูน matrix ต้องคำนึงถึง dimension นะ

array([[14, 32],
       [32, 77]])

In [8]:
A.dot(A)

ValueError: ignored

#Array slicing

In [9]:
A[0,1]  #ชี้ตำแหน่งของสมากชิก โดยแถวกับหลัก

2

In [11]:
A[:,:2] # sclice แถวที่ : ถึงแถวที่ , หละหที่ : หลักที่

array([[1, 2],
       [4, 5]])

In [14]:
A[1,1:]

array([5, 6])

In [15]:
#HW 6 : สร้าง distance metrix (Euclidean) ของ data matrix ใน slides โดยโครงสร้าง function 

In [19]:
data_1 = np.array([[1,2],[3,5],[2,0],[4,5]])

In [20]:
data_1

array([[1, 2],
       [3, 5],
       [2, 0],
       [4, 5]])

In [22]:
def Manhattan_dist(dp1,dp2):
    distX = abs(dp1[0]-dp2[0])
    distY = abs(dp1[1]-dp2[1])
    return distX+distY

In [23]:
np.zeros((4,4)) #สร้าง array ว่างที่มีขนาด 4แถว * 4หลัก

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
np.ones((4,4))  #identity metrix ใช้สร้าง matrix ค่าคงที่ โดยการเอา scalar มาคูณ

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
7*np.ones((4,4)) 

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

In [25]:
dist_mat_man = np.zeros((4,4))
dist_mat_man

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [26]:
for i in range(4):
  for j in range(4):
      dist_mat_man[i,j] = Manhattan_dist(data_1[i,:],data_1[j,:])
dist_mat_man

array([[0., 5., 3., 6.],
       [5., 0., 6., 1.],
       [3., 6., 0., 7.],
       [6., 1., 7., 0.]])