<a href="https://colab.research.google.com/github/K-Kamonrat/DPDM/blob/master/Data103.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np #จัดการตัวเลข มองเป็น matrix

In [ ]:
A = np.array([[1,2,3],[4,5,6]]) #พิมพ์แถวเรียงต่อกัน
A

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
A.T #transpost

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
A.dot(A.T) #.dot()  การคูน matrix ต้องคำนึงถึง dimension นะ

array([[14, 32],
       [32, 77]])

In [ ]:
A.dot(A)

ValueError: ignored

#Array slicing

In [ ]:
A[0,1]  #ชี้ตำแหน่งของสมากชิก โดยแถวกับหลัก

2

In [ ]:
A[:,:2] # sclice แถวที่ : ถึงแถวที่ , หละหที่ : หลักที่

array([[1, 2],
       [4, 5]])

In [ ]:
A[1,1:]

array([5, 6])

#HW 6 : สร้าง distance metrix (Euclidean) ของ data matrix ใน slides โดยโครงสร้าง function 

In [ ]:
data_1 = np.array([[1,2],[3,5],[2,0],[4,5]])

In [ ]:
data_1

array([[1, 2],
       [3, 5],
       [2, 0],
       [4, 5]])

In [ ]:
def Manhattan_dist(dp1,dp2):
    distX = abs(dp1[0]-dp2[0])
    distY = abs(dp1[1]-dp2[1])
    return distX+distY

In [ ]:
np.zeros((4,4)) #สร้าง array ว่างที่มีขนาด 4แถว * 4หลัก

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((4,4))  #identity metrix ใช้สร้าง matrix ค่าคงที่ โดยการเอา scalar มาคูณ

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
7*np.ones((4,4)) 

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

In [ ]:
dist_mat_man = np.zeros((4,4))
dist_mat_man

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
for i in range(4):
  for j in range(4):
      dist_mat_man[i,j] = Manhattan_dist(data_1[i,:],data_1[j,:])
dist_mat_man

array([[0., 5., 3., 6.],
       [5., 0., 6., 1.],
       [3., 6., 0., 7.],
       [6., 1., 7., 0.]])

##ส่งการบ้าน Euclidean distance

In [ ]:
# import the math module  
import math  
  
# print the square root of  0  
print(math.sqrt(4)) 

2.0


In [ ]:
A = np.array([[1,2],[3,5],[2,0],[4,5]])

In [ ]:
A

array([[1, 2],
       [3, 5],
       [2, 0],
       [4, 5]])

In [ ]:
def Euclidean_dist(p1,p2):
    dist_r = abs(p1[0]-p2[0])
    dist_c = abs(p1[1]-p2[1])
    return math.sqrt(dist_r**2 + dist_c**2)

In [ ]:
dist_mat_Euclidean = np.zeros((4,4))
dist_mat_Euclidean

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
for i in range(4):
  for j in range(4):
      dist_mat_Euclidean[i,j] = Euclidean_dist(A[i,:],A[j,:])
dist_mat_Euclidean

array([[0.        , 3.60555128, 2.23606798, 4.24264069],
       [3.60555128, 0.        , 5.09901951, 1.        ],
       [2.23606798, 5.09901951, 0.        , 5.38516481],
       [4.24264069, 1.        , 5.38516481, 0.        ]])

#Distance of nominal or categorical feature
##(extra) Python data structure (Dictionary)
* คล้ายๆ list แต่ไม่ได้ชี้ตำแหน่งด้วยตัวเลข อาจจะชี้ด้วยตัวอักษร หรืออะไรก็ได้ แต่ต้องไม่เป็นตัวแปร
* ไม่สนใจลำดับ
* เก็บข้อมูลได้ทั้ง string list

In [1]:
d_A = {'a':1,2:3,3:3,3:5,'cat':6}  #เริ่มด้วยตัวชี้index : ค่าที่เก็บมา

In [2]:
d_A

{2: 3, 3: 5, 'a': 1, 'cat': 6}

In [3]:
d_A['cat']

6

In [4]:
d_A['dog'] = [1,2,3,4,5] #การเพิ่มสมาชิก ==> ชื่อdict[index] = [ค่าที่อยู่ในindexนั้น]

In [5]:
d_A

{2: 3, 3: 5, 'a': 1, 'cat': 6, 'dog': [1, 2, 3, 4, 5]}

In [6]:
del d_A[2] #ลบข้อมูลออกจาก dict แต่ปกติก็ไม่ควรลบ

In [8]:
d_A

{3: 5, 'a': 1, 'cat': 6, 'dog': [1, 2, 3, 4, 5]}

In [9]:
import pandas as pd

In [11]:
data_dict = {'color':['red','red','green'], #color = {'red','green',blue'}
                    'status':['single','married','single']} #status = {'single','married','divorced'}
data_dict

{'color': ['red', 'red', 'green'], 'status': ['single', 'married', 'single']}

In [12]:
data_pd = pd.DataFrame.from_dict(data_dict)
data_pd

color   status
0    red   single
1    red  married
2  green   single

##Categorical feature distance method#*1*

In [13]:
list(data_pd.iloc[1,:]) #iloc เปลี่ยนมุมมองของตารางของ pandas ให้เป็น numpy array

['red', 'married']

In [24]:
def meth1_dist(data1,data2):
  N = 0 #สร้างตัวแปรมาเก็บสิ่งที่จะนับ
  print(f'data1 is{data1} and data2 is {data2}')
  for i in range(len(data1)): #สร้างลูป ตามขนาดของ feature
    print(f'feature{i} of data1 is {data1[i]},feature{i} of data2 is {data2[i]}')
    if data1[i] != data2[i]:
      N = N+1
      print(f'     {data1[i]} is not equal {data2[i]} : updated ({N})')
    else:
      print(f'           {data1[i]}  is equal {data2[i]} ')
  return N/len(data1)


In [25]:
meth1_dist(list(data_pd.iloc[0,:]),list(data_pd.iloc[1,:]))

data1 is['red', 'single'] and data2 is ['red', 'married']
feature0 of data1 is red,feature0 of data2 is red
           red  is equal red 
feature1 of data1 is single,feature1 of data2 is married
     single is not equal married : updated (1)


0.5

#HW Calculate distance matrix of data_pd using  meth1_dist()

In [26]:
import numpy as np #จัดการตัวเลข มองเป็น matrix

In [29]:
dist_meth1_nominal = np.zeros((3,3))
dist_meth1_nominal

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [31]:
data_pd

color   status
0    red   single
1    red  married
2  green   single

In [32]:
for i in range(3):
  for j in range(3):
      dist_meth1_nominal[i,j] = meth1_dist(list(data_pd.iloc[i,:]),list(data_pd.iloc[j,:]))
dist_meth1_nominal

data1 is['red', 'single'] and data2 is ['red', 'single']
feature0 of data1 is red,feature0 of data2 is red
           red  is equal red 
feature1 of data1 is single,feature1 of data2 is single
           single  is equal single 
data1 is['red', 'single'] and data2 is ['red', 'married']
feature0 of data1 is red,feature0 of data2 is red
           red  is equal red 
feature1 of data1 is single,feature1 of data2 is married
     single is not equal married : updated (1)
data1 is['red', 'single'] and data2 is ['green', 'single']
feature0 of data1 is red,feature0 of data2 is green
     red is not equal green : updated (1)
feature1 of data1 is single,feature1 of data2 is single
           single  is equal single 
data1 is['red', 'married'] and data2 is ['red', 'single']
feature0 of data1 is red,feature0 of data2 is red
           red  is equal red 
feature1 of data1 is married,feature1 of data2 is single
     married is not equal single : updated (1)
data1 is['red', 'married'] and data2 is ['

array([[0. , 0.5, 0.5],
       [0.5, 0. , 1. ],
       [0.5, 1. , 0. ]])

##Categorical feature distance method#*2*

In [34]:
data_pd #ตอนนี้ data เรามีแค่ featur ละ 2 ค่า แต่จริงๆแล้ว featur color มี 3 ค่าที่เป็นไปได้  >> red blue green // status ก็เหมือนกัน

color   status
0    red   single
1    red  married
2  green   single

In [37]:
data_dict2 = {'color':['red','red','green','blue'], #color = {'red','green',blue'}
                    'status':['single','married','single','divorced']} #status = {'single','married','divorced'}
data_pd2 = pd.DataFrame.from_dict(data_dict2)
data_pd2

color    status
0    red    single
1    red   married
2  green    single
3   blue  divorced

In [39]:
data_pd_binary = pd.get_dummies(data_pd2) #pd.get มันจะสร้างตาราง binary มาให้
data_pd_binary = data_pd_binary.iloc[:3,:]
data_pd_binary

color_blue  color_green  ...  status_married  status_single
0           0            0  ...               0              1
1           0            0  ...               1              0
2           0            1  ...               0              1

[3 rows x 6 columns]

In [53]:
#เนื่องจาก data ของเราไม่ใช่ข้อมูลทางการแพทย์ เราจะใช้สูตร symetry
def binary_sym_dist(data1,data2):
    r = 0
    s = 0
    t = 0
    q = 0
    for i in range(len(data1)): #วนลูปตามจำนวน feature จะใช้ len(data1 หรือ data2 ก็ได้) เพราะทั้งสองมีจำนวน feature เท่ากัน
          if data1[i] != data2[i]: #case1 checkกรณีที่ไม่เท่ากัน #ตอนนี้เรารู้แล้วว่าตัวที่ i ของdata1ไม่เท่ากับdata2
                if data1[i] == 0:  #ถ้าตัวแรกเป็น 0 เราจะ update s
                      s = s+1
                else:
                      r = r+1
          else:
                if data1[i] == 0: #case2 checkกรณีที่เท่ากัน 
                      t = t+1
                else:
                      q = q+1
    return (r+s) / (r+s+t+q)

In [55]:
binary_sym_dist (list(data_pd_binary.iloc[0,:]),list(data_pd_binary.iloc[1,:]))

0.3333333333333333

#HW8 calculate distance matrix of data_pd_binary using binate_sym_dist()

In [56]:
data_pd_binary

color_blue  color_green  ...  status_married  status_single
0           0            0  ...               0              1
1           0            0  ...               1              0
2           0            1  ...               0              1

[3 rows x 6 columns]

In [ ]:
dist_binary

In [60]:
dist_binary = np.zeros((3,3))
dist_binary

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [62]:
for i in range(3):
  for j in range(3):
      dist_binary[i,j] = binary_sym_dist(list(data_pd_binary.iloc[0,:]),list(data_pd_binary.iloc[1,:]))


In [63]:
dist_binary

array([[0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333]])