<a href="https://colab.research.google.com/github/K-Kamonrat/DPDM/blob/master/Data103.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np #จัดการตัวเลข มองเป็น matrix

In [3]:
A = np.array([[1,2,3],[4,5,6]]) #พิมพ์แถวเรียงต่อกัน
A

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
A.T #transpost

array([[1, 4],
       [2, 5],
       [3, 6]])

In [5]:
A.dot(A.T) #.dot()  การคูน matrix ต้องคำนึงถึง dimension นะ

array([[14, 32],
       [32, 77]])

In [6]:
A.dot(A)

ValueError: ignored

#Array slicing

In [7]:
A[0,1]  #ชี้ตำแหน่งของสมากชิก โดยแถวกับหลัก

2

In [8]:
A[:,:2] # sclice แถวที่ : ถึงแถวที่ , หละหที่ : หลักที่

array([[1, 2],
       [4, 5]])

In [9]:
A[1,1:]

array([5, 6])

#HW 6 : สร้าง distance metrix (Euclidean) ของ data matrix ใน slides โดยโครงสร้าง function 

In [11]:
data_1 = np.array([[1,2],[3,5],[2,0],[4,5]])

In [12]:
data_1

array([[1, 2],
       [3, 5],
       [2, 0],
       [4, 5]])

In [13]:
def Manhattan_dist(dp1,dp2):
    distX = abs(dp1[0]-dp2[0])
    distY = abs(dp1[1]-dp2[1])
    return distX+distY

In [14]:
np.zeros((4,4)) #สร้าง array ว่างที่มีขนาด 4แถว * 4หลัก

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.ones((4,4))  #identity metrix ใช้สร้าง matrix ค่าคงที่ โดยการเอา scalar มาคูณ

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
7*np.ones((4,4)) 

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

In [17]:
dist_mat_man = np.zeros((4,4))
dist_mat_man

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
for i in range(4):
  for j in range(4):
      dist_mat_man[i,j] = Manhattan_dist(data_1[i,:],data_1[j,:])
dist_mat_man

array([[0., 5., 3., 6.],
       [5., 0., 6., 1.],
       [3., 6., 0., 7.],
       [6., 1., 7., 0.]])

##ส่งการบ้าน Euclidean distance

In [25]:
# import the math module  
import math  
  
# print the square root of  0  
print(math.sqrt(4)) 

2.0


In [19]:
A = np.array([[1,2],[3,5],[2,0],[4,5]])

In [20]:
A

array([[1, 2],
       [3, 5],
       [2, 0],
       [4, 5]])

In [26]:
def Euclidean_dist(p1,p2):
    dist_r = abs(p1[0]-p2[0])
    dist_c = abs(p1[1]-p2[1])
    return math.sqrt(dist_r**2 + dist_c**2)

In [27]:
dist_mat_Euclidean = np.zeros((4,4))
dist_mat_Euclidean

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
for i in range(4):
  for j in range(4):
      dist_mat_Euclidean[i,j] = Euclidean_dist(A[i,:],A[j,:])
dist_mat_Euclidean

array([[0.        , 3.60555128, 2.23606798, 4.24264069],
       [3.60555128, 0.        , 5.09901951, 1.        ],
       [2.23606798, 5.09901951, 0.        , 5.38516481],
       [4.24264069, 1.        , 5.38516481, 0.        ]])